package com.weychain.erp.mapper;

import java.util.List;

import com.weychain.erp.domain.example.DepotHeadExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.weychain.erp.domain.DO.DepotHead;
@Mapper
public interface DepotHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbggenerated
     */
    int countByExample(DepotHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbggenerated
     */
    int deleteByExample(DepotHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbggenerated
     */
    int insert(DepotHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbggenerated
     */
    int insertSelective(DepotHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbggenerated
     */
    List<DepotHead> selectByExample(DepotHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbggenerated
     */
    DepotHead selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DepotHead record, @Param("example") DepotHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DepotHead record, @Param("example") DepotHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DepotHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DepotHead record);
}