package com.weychain.erp.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.weychain.erp.domain.DO.ERP_Account;

import java.util.List;

import com.weychain.erp.domain.example.ERP_AccountExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ERP_AccountMapper extends BaseMapper<ERP_Account> {

    /**
     * 查询账户信息
     * @return
     */

    List<ERP_Account> queryErpAccountList ();
    /**
     * 新增账户信息
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_account
     *
     * @mbggenerated
     */
    int countByExample(ERP_AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_account
     *
     * @mbggenerated
     */
    int deleteByExample(ERP_AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_account
     *
     * @mbggenerated
     */
    int insert(ERP_Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_account
     *
     * @mbggenerated
     */
    int insertSelective(ERP_Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_account
     *
     * @mbggenerated
     */
    List<ERP_Account> selectByExample(ERP_AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_account
     *
     * @mbggenerated
     */
    ERP_Account selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ERP_Account record, @Param("example") ERP_AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ERP_Account record, @Param("example") ERP_AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ERP_Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ERP_Account record);
}