package com.weychain.erp.mapper;

import java.util.List;

import com.weychain.erp.domain.example.MaterialPropertyExample;
import org.apache.ibatis.annotations.Param;

import com.weychain.erp.domain.DO.MaterialProperty;

public interface MaterialPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbggenerated
     */
    int countByExample(MaterialPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbggenerated
     */
    int deleteByExample(MaterialPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbggenerated
     */
    int insert(MaterialProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbggenerated
     */
    int insertSelective(MaterialProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbggenerated
     */
    List<MaterialProperty> selectByExample(MaterialPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbggenerated
     */
    MaterialProperty selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MaterialProperty record, @Param("example") MaterialPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MaterialProperty record, @Param("example") MaterialPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MaterialProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MaterialProperty record);
}