package com.weychain.erp.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.weychain.erp.domain.DO.OrganTypeName;

import java.util.List;

import com.weychain.erp.domain.example.OrganTypeNameExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface OrganTypeNameMapper extends BaseMapper<OrganTypeName> {
    /**
     * 查询机构类型名称列表
     * @return
     */
    List<OrganTypeName> queryOrganTypeNameList();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization_name
     *
     * @mbggenerated
     */
    int countByExample(OrganTypeNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization_name
     *
     * @mbggenerated
     */
    int deleteByExample(OrganTypeNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization_name
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization_name
     *
     * @mbggenerated
     */
    int insert(OrganTypeName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization_name
     *
     * @mbggenerated
     */
    int insertSelective(OrganTypeName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization_name
     *
     * @mbggenerated
     */
    List<OrganTypeName> selectByExample(OrganTypeNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization_name
     *
     * @mbggenerated
     */
    OrganTypeName selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization_name
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrganTypeName record, @Param("example") OrganTypeNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization_name
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrganTypeName record, @Param("example") OrganTypeNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization_name
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrganTypeName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization_name
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrganTypeName record);
}