package com.weychain.erp.mapper;

<<<<<<< HEAD
import com.weychain.erp.domain.DO.Unit;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface UnitMapper {

    int countByExample(Unit example);


    int deleteByExample(Unit example);


    int deleteByPrimaryKey(Long id);


    int insert(Unit record);


    int insertSelective(Unit record);


    List<Unit> selectByExample(Unit example);


    Unit selectByPrimaryKey(Long id);


    int updateByExampleSelective(@Param("record") Unit record, @Param("example") Unit example);


    int updateByExample(@Param("record") Unit record, @Param("example") Unit example);


    int updateByPrimaryKeySelective(Unit record);


=======
import java.util.List;

import com.weychain.erp.domain.example.UnitExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.weychain.erp.domain.DO.Unit;
@Mapper
public interface UnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbggenerated
     */
    int countByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbggenerated
     */
    int deleteByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbggenerated
     */
    int insert(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbggenerated
     */
    int insertSelective(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbggenerated
     */
    List<Unit> selectByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbggenerated
     */
    Unit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Unit record, @Param("example") UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Unit record, @Param("example") UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbggenerated
     */
>>>>>>> d55d0fe9e143a7b7fe4f5ca36e71a433c102f9b6
    int updateByPrimaryKey(Unit record);
}