package com.weychain.erp.mapper;

<<<<<<< HEAD
import com.weychain.erp.domain.DO.UserBusiness;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface UserBusinessMapper {

    int countByExample(UserBusiness example);


    int deleteByExample(UserBusiness example);


    int deleteByPrimaryKey(Long id);


    int insert(UserBusiness record);


    int insertSelective(UserBusiness record);


    List<UserBusiness> selectByExample(UserBusiness example);


    UserBusiness selectByPrimaryKey(Long id);


    int updateByExampleSelective(@Param("record") UserBusiness record, @Param("example") UserBusiness example);


    int updateByExample(@Param("record") UserBusiness record, @Param("example") UserBusiness example);


    int updateByPrimaryKeySelective(UserBusiness record);


=======
import java.util.List;

import com.weychain.erp.domain.example.UserBusinessExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.weychain.erp.domain.DO.UserBusiness;
@Mapper
public interface UserBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbggenerated
     */
    int countByExample(UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbggenerated
     */
    int deleteByExample(UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbggenerated
     */
    int insert(UserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbggenerated
     */
    int insertSelective(UserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbggenerated
     */
    List<UserBusiness> selectByExample(UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbggenerated
     */
    UserBusiness selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserBusiness record, @Param("example") UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserBusiness record, @Param("example") UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbggenerated
     */
>>>>>>> d55d0fe9e143a7b7fe4f5ca36e71a433c102f9b6
    int updateByPrimaryKey(UserBusiness record);
}