package com.weychain.erp.domain.DO;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_address.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_address.add_country
     *
     * @mbggenerated
     */
    private String addCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_address.add_province
     *
     * @mbggenerated
     */
    private String addProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_address.add_city
     *
     * @mbggenerated
     */
    private String addCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_address.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_address.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_address.tenant_id
     *
     * @mbggenerated
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_address.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_address.creat_time
     *
     * @mbggenerated
     */
    private String creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_address.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_address.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_address.id
     *
     * @return the value of erp_address.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_address.id
     *
     * @param id the value for erp_address.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_address.add_country
     *
     * @return the value of erp_address.add_country
     *
     * @mbggenerated
     */
    public String getAddCountry() {
        return addCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_address.add_country
     *
     * @param addCountry the value for erp_address.add_country
     *
     * @mbggenerated
     */
    public void setAddCountry(String addCountry) {
        this.addCountry = addCountry == null ? null : addCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_address.add_province
     *
     * @return the value of erp_address.add_province
     *
     * @mbggenerated
     */
    public String getAddProvince() {
        return addProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_address.add_province
     *
     * @param addProvince the value for erp_address.add_province
     *
     * @mbggenerated
     */
    public void setAddProvince(String addProvince) {
        this.addProvince = addProvince == null ? null : addProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_address.add_city
     *
     * @return the value of erp_address.add_city
     *
     * @mbggenerated
     */
    public String getAddCity() {
        return addCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_address.add_city
     *
     * @param addCity the value for erp_address.add_city
     *
     * @mbggenerated
     */
    public void setAddCity(String addCity) {
        this.addCity = addCity == null ? null : addCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_address.email
     *
     * @return the value of erp_address.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_address.email
     *
     * @param email the value for erp_address.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_address.address
     *
     * @return the value of erp_address.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_address.address
     *
     * @param address the value for erp_address.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_address.tenant_id
     *
     * @return the value of erp_address.tenant_id
     *
     * @mbggenerated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_address.tenant_id
     *
     * @param tenantId the value for erp_address.tenant_id
     *
     * @mbggenerated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_address.creator
     *
     * @return the value of erp_address.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_address.creator
     *
     * @param creator the value for erp_address.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_address.creat_time
     *
     * @return the value of erp_address.creat_time
     *
     * @mbggenerated
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_address.creat_time
     *
     * @param creatTime the value for erp_address.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime == null ? null : creatTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_address.updater
     *
     * @return the value of erp_address.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_address.updater
     *
     * @param updater the value for erp_address.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_address.update_time
     *
     * @return the value of erp_address.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_address.update_time
     *
     * @param updateTime the value for erp_address.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}