package com.weychain.erp.domain.DO;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_city.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_city.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_city.city_code
     *
     * @mbggenerated
     */
    private Integer cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_city.province_code
     *
     * @mbggenerated
     */
    private Integer provinceCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_city.id
     *
     * @return the value of erp_city.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_city.id
     *
     * @param id the value for erp_city.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_city.name
     *
     * @return the value of erp_city.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_city.name
     *
     * @param name the value for erp_city.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_city.city_code
     *
     * @return the value of erp_city.city_code
     *
     * @mbggenerated
     */
    public Integer getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_city.city_code
     *
     * @param cityCode the value for erp_city.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(Integer cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_city.province_code
     *
     * @return the value of erp_city.province_code
     *
     * @mbggenerated
     */
    public Integer getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_city.province_code
     *
     * @param provinceCode the value for erp_city.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(Integer provinceCode) {
        this.provinceCode = provinceCode;
    }
}