package com.weychain.erp.domain.DO;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.company_id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.company_img
     *
     * @mbggenerated
     */
    private String companyImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.company_telephone
     *
     * @mbggenerated
     */
    private String companyTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.mark_registration_no
     *
     * @mbggenerated
     */
    private Integer markRegistrationNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.tax_code
     *
     * @mbggenerated
     */
    private String taxCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.e_mail
     *
     * @mbggenerated
     */
    private String eMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.website
     *
     * @mbggenerated
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.company_type
     *
     * @mbggenerated
     */
    private String companyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.company_address
     *
     * @mbggenerated
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.company_power
     *
     * @mbggenerated
     */
    private String companyPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.company_corporation
     *
     * @mbggenerated
     */
    private String companyCorporation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.duty_no
     *
     * @mbggenerated
     */
    private Integer dutyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.management_model
     *
     * @mbggenerated
     */
    private String managementModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.annual_turnove
     *
     * @mbggenerated
     */
    private String annualTurnove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.registered_capital
     *
     * @mbggenerated
     */
    private String registeredCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.tenant_id
     *
     * @mbggenerated
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.account_id
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.address_id
     *
     * @mbggenerated
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_company.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.company_id
     *
     * @return the value of erp_company.company_id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.company_id
     *
     * @param companyId the value for erp_company.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.company_name
     *
     * @return the value of erp_company.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.company_name
     *
     * @param companyName the value for erp_company.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.company_img
     *
     * @return the value of erp_company.company_img
     *
     * @mbggenerated
     */
    public String getCompanyImg() {
        return companyImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.company_img
     *
     * @param companyImg the value for erp_company.company_img
     *
     * @mbggenerated
     */
    public void setCompanyImg(String companyImg) {
        this.companyImg = companyImg == null ? null : companyImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.company_telephone
     *
     * @return the value of erp_company.company_telephone
     *
     * @mbggenerated
     */
    public String getCompanyTelephone() {
        return companyTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.company_telephone
     *
     * @param companyTelephone the value for erp_company.company_telephone
     *
     * @mbggenerated
     */
    public void setCompanyTelephone(String companyTelephone) {
        this.companyTelephone = companyTelephone == null ? null : companyTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.mark_registration_no
     *
     * @return the value of erp_company.mark_registration_no
     *
     * @mbggenerated
     */
    public Integer getMarkRegistrationNo() {
        return markRegistrationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.mark_registration_no
     *
     * @param markRegistrationNo the value for erp_company.mark_registration_no
     *
     * @mbggenerated
     */
    public void setMarkRegistrationNo(Integer markRegistrationNo) {
        this.markRegistrationNo = markRegistrationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.fax
     *
     * @return the value of erp_company.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.fax
     *
     * @param fax the value for erp_company.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.tax_code
     *
     * @return the value of erp_company.tax_code
     *
     * @mbggenerated
     */
    public String getTaxCode() {
        return taxCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.tax_code
     *
     * @param taxCode the value for erp_company.tax_code
     *
     * @mbggenerated
     */
    public void setTaxCode(String taxCode) {
        this.taxCode = taxCode == null ? null : taxCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.e_mail
     *
     * @return the value of erp_company.e_mail
     *
     * @mbggenerated
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.e_mail
     *
     * @param eMail the value for erp_company.e_mail
     *
     * @mbggenerated
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.website
     *
     * @return the value of erp_company.website
     *
     * @mbggenerated
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.website
     *
     * @param website the value for erp_company.website
     *
     * @mbggenerated
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.company_type
     *
     * @return the value of erp_company.company_type
     *
     * @mbggenerated
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.company_type
     *
     * @param companyType the value for erp_company.company_type
     *
     * @mbggenerated
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType == null ? null : companyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.company_address
     *
     * @return the value of erp_company.company_address
     *
     * @mbggenerated
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.company_address
     *
     * @param companyAddress the value for erp_company.company_address
     *
     * @mbggenerated
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.company_power
     *
     * @return the value of erp_company.company_power
     *
     * @mbggenerated
     */
    public String getCompanyPower() {
        return companyPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.company_power
     *
     * @param companyPower the value for erp_company.company_power
     *
     * @mbggenerated
     */
    public void setCompanyPower(String companyPower) {
        this.companyPower = companyPower == null ? null : companyPower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.company_corporation
     *
     * @return the value of erp_company.company_corporation
     *
     * @mbggenerated
     */
    public String getCompanyCorporation() {
        return companyCorporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.company_corporation
     *
     * @param companyCorporation the value for erp_company.company_corporation
     *
     * @mbggenerated
     */
    public void setCompanyCorporation(String companyCorporation) {
        this.companyCorporation = companyCorporation == null ? null : companyCorporation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.duty_no
     *
     * @return the value of erp_company.duty_no
     *
     * @mbggenerated
     */
    public Integer getDutyNo() {
        return dutyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.duty_no
     *
     * @param dutyNo the value for erp_company.duty_no
     *
     * @mbggenerated
     */
    public void setDutyNo(Integer dutyNo) {
        this.dutyNo = dutyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.management_model
     *
     * @return the value of erp_company.management_model
     *
     * @mbggenerated
     */
    public String getManagementModel() {
        return managementModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.management_model
     *
     * @param managementModel the value for erp_company.management_model
     *
     * @mbggenerated
     */
    public void setManagementModel(String managementModel) {
        this.managementModel = managementModel == null ? null : managementModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.annual_turnove
     *
     * @return the value of erp_company.annual_turnove
     *
     * @mbggenerated
     */
    public String getAnnualTurnove() {
        return annualTurnove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.annual_turnove
     *
     * @param annualTurnove the value for erp_company.annual_turnove
     *
     * @mbggenerated
     */
    public void setAnnualTurnove(String annualTurnove) {
        this.annualTurnove = annualTurnove == null ? null : annualTurnove.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.registered_capital
     *
     * @return the value of erp_company.registered_capital
     *
     * @mbggenerated
     */
    public String getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.registered_capital
     *
     * @param registeredCapital the value for erp_company.registered_capital
     *
     * @mbggenerated
     */
    public void setRegisteredCapital(String registeredCapital) {
        this.registeredCapital = registeredCapital == null ? null : registeredCapital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.tenant_id
     *
     * @return the value of erp_company.tenant_id
     *
     * @mbggenerated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.tenant_id
     *
     * @param tenantId the value for erp_company.tenant_id
     *
     * @mbggenerated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.account_id
     *
     * @return the value of erp_company.account_id
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.account_id
     *
     * @param accountId the value for erp_company.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.address_id
     *
     * @return the value of erp_company.address_id
     *
     * @mbggenerated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.address_id
     *
     * @param addressId the value for erp_company.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.creator
     *
     * @return the value of erp_company.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.creator
     *
     * @param creator the value for erp_company.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.create_time
     *
     * @return the value of erp_company.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.create_time
     *
     * @param createTime the value for erp_company.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.updater
     *
     * @return the value of erp_company.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.updater
     *
     * @param updater the value for erp_company.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_company.update_time
     *
     * @return the value of erp_company.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_company.update_time
     *
     * @param updateTime the value for erp_company.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}