package com.weychain.erp.domain.DO;

public class ERP_Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_account.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_account.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_account.deposit_bank
     *
     * @mbggenerated
     */
    private String depositBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_account.account_No
     *
     * @mbggenerated
     */
    private Integer accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_account.account_type
     *
     * @mbggenerated
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_account.account_status
     *
     * @mbggenerated
     */
    private String accountStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_account.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_account.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_account.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_account.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_account.id
     *
     * @return the value of erp_account.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_account.id
     *
     * @param id the value for erp_account.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_account.name
     *
     * @return the value of erp_account.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_account.name
     *
     * @param name the value for erp_account.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_account.deposit_bank
     *
     * @return the value of erp_account.deposit_bank
     *
     * @mbggenerated
     */
    public String getDepositBank() {
        return depositBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_account.deposit_bank
     *
     * @param depositBank the value for erp_account.deposit_bank
     *
     * @mbggenerated
     */
    public void setDepositBank(String depositBank) {
        this.depositBank = depositBank == null ? null : depositBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_account.account_No
     *
     * @return the value of erp_account.account_No
     *
     * @mbggenerated
     */
    public Integer getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_account.account_No
     *
     * @param accountNo the value for erp_account.account_No
     *
     * @mbggenerated
     */
    public void setAccountNo(Integer accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_account.account_type
     *
     * @return the value of erp_account.account_type
     *
     * @mbggenerated
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_account.account_type
     *
     * @param accountType the value for erp_account.account_type
     *
     * @mbggenerated
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_account.account_status
     *
     * @return the value of erp_account.account_status
     *
     * @mbggenerated
     */
    public String getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_account.account_status
     *
     * @param accountStatus the value for erp_account.account_status
     *
     * @mbggenerated
     */
    public void setAccountStatus(String accountStatus) {
        this.accountStatus = accountStatus == null ? null : accountStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_account.creator
     *
     * @return the value of erp_account.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_account.creator
     *
     * @param creator the value for erp_account.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_account.create_time
     *
     * @return the value of erp_account.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_account.create_time
     *
     * @param createTime the value for erp_account.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_account.updater
     *
     * @return the value of erp_account.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_account.updater
     *
     * @param updater the value for erp_account.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_account.update_time
     *
     * @return the value of erp_account.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_account.update_time
     *
     * @param updateTime the value for erp_account.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}