package com.weychain.erp.domain.DO;

public class OrganTypeName {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_organization_name.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_organization_name.org_type_name
     *
     * @mbggenerated
     */
    private String orgTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_organization_name.tenant_id
     *
     * @mbggenerated
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_organization_name.organ_code
     *
     * @mbggenerated
     */
    private String organCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_organization_name.creat_time
     *
     * @mbggenerated
     */
    private String creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_organization_name.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_organization_name.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_organization_name.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_organization_name.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_organization_name.id
     *
     * @return the value of jsh_organization_name.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_organization_name.id
     *
     * @param id the value for jsh_organization_name.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_organization_name.org_type_name
     *
     * @return the value of jsh_organization_name.org_type_name
     *
     * @mbggenerated
     */
    public String getOrgTypeName() {
        return orgTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_organization_name.org_type_name
     *
     * @param orgTypeName the value for jsh_organization_name.org_type_name
     *
     * @mbggenerated
     */
    public void setOrgTypeName(String orgTypeName) {
        this.orgTypeName = orgTypeName == null ? null : orgTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_organization_name.tenant_id
     *
     * @return the value of jsh_organization_name.tenant_id
     *
     * @mbggenerated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_organization_name.tenant_id
     *
     * @param tenantId the value for jsh_organization_name.tenant_id
     *
     * @mbggenerated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_organization_name.organ_code
     *
     * @return the value of jsh_organization_name.organ_code
     *
     * @mbggenerated
     */
    public String getOrganCode() {
        return organCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_organization_name.organ_code
     *
     * @param organCode the value for jsh_organization_name.organ_code
     *
     * @mbggenerated
     */
    public void setOrganCode(String organCode) {
        this.organCode = organCode == null ? null : organCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_organization_name.creat_time
     *
     * @return the value of jsh_organization_name.creat_time
     *
     * @mbggenerated
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_organization_name.creat_time
     *
     * @param creatTime the value for jsh_organization_name.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime == null ? null : creatTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_organization_name.parent_id
     *
     * @return the value of jsh_organization_name.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_organization_name.parent_id
     *
     * @param parentId the value for jsh_organization_name.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_organization_name.creator
     *
     * @return the value of jsh_organization_name.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_organization_name.creator
     *
     * @param creator the value for jsh_organization_name.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_organization_name.update_time
     *
     * @return the value of jsh_organization_name.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_organization_name.update_time
     *
     * @param updateTime the value for jsh_organization_name.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_organization_name.updater
     *
     * @return the value of jsh_organization_name.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_organization_name.updater
     *
     * @param updater the value for jsh_organization_name.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}