package com.weychain.erp.domain.DO;

public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_province.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_province.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_province.province_code
     *
     * @mbggenerated
     */
    private Integer provinceCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_province.id
     *
     * @return the value of erp_province.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_province.id
     *
     * @param id the value for erp_province.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_province.name
     *
     * @return the value of erp_province.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_province.name
     *
     * @param name the value for erp_province.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_province.province_code
     *
     * @return the value of erp_province.province_code
     *
     * @mbggenerated
     */
    public Integer getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_province.province_code
     *
     * @param provinceCode the value for erp_province.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(Integer provinceCode) {
        this.provinceCode = provinceCode;
    }
}