package com.weychain.erp.domain.example;

import java.util.ArrayList;
import java.util.List;

public class CompanyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    public CompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Integer value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Integer value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Integer value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Integer value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Integer> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Integer> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyImgIsNull() {
            addCriterion("company_img is null");
            return (Criteria) this;
        }

        public Criteria andCompanyImgIsNotNull() {
            addCriterion("company_img is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyImgEqualTo(String value) {
            addCriterion("company_img =", value, "companyImg");
            return (Criteria) this;
        }

        public Criteria andCompanyImgNotEqualTo(String value) {
            addCriterion("company_img <>", value, "companyImg");
            return (Criteria) this;
        }

        public Criteria andCompanyImgGreaterThan(String value) {
            addCriterion("company_img >", value, "companyImg");
            return (Criteria) this;
        }

        public Criteria andCompanyImgGreaterThanOrEqualTo(String value) {
            addCriterion("company_img >=", value, "companyImg");
            return (Criteria) this;
        }

        public Criteria andCompanyImgLessThan(String value) {
            addCriterion("company_img <", value, "companyImg");
            return (Criteria) this;
        }

        public Criteria andCompanyImgLessThanOrEqualTo(String value) {
            addCriterion("company_img <=", value, "companyImg");
            return (Criteria) this;
        }

        public Criteria andCompanyImgLike(String value) {
            addCriterion("company_img like", value, "companyImg");
            return (Criteria) this;
        }

        public Criteria andCompanyImgNotLike(String value) {
            addCriterion("company_img not like", value, "companyImg");
            return (Criteria) this;
        }

        public Criteria andCompanyImgIn(List<String> values) {
            addCriterion("company_img in", values, "companyImg");
            return (Criteria) this;
        }

        public Criteria andCompanyImgNotIn(List<String> values) {
            addCriterion("company_img not in", values, "companyImg");
            return (Criteria) this;
        }

        public Criteria andCompanyImgBetween(String value1, String value2) {
            addCriterion("company_img between", value1, value2, "companyImg");
            return (Criteria) this;
        }

        public Criteria andCompanyImgNotBetween(String value1, String value2) {
            addCriterion("company_img not between", value1, value2, "companyImg");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneIsNull() {
            addCriterion("company_telephone is null");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneIsNotNull() {
            addCriterion("company_telephone is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneEqualTo(String value) {
            addCriterion("company_telephone =", value, "companyTelephone");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneNotEqualTo(String value) {
            addCriterion("company_telephone <>", value, "companyTelephone");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneGreaterThan(String value) {
            addCriterion("company_telephone >", value, "companyTelephone");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("company_telephone >=", value, "companyTelephone");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneLessThan(String value) {
            addCriterion("company_telephone <", value, "companyTelephone");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneLessThanOrEqualTo(String value) {
            addCriterion("company_telephone <=", value, "companyTelephone");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneLike(String value) {
            addCriterion("company_telephone like", value, "companyTelephone");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneNotLike(String value) {
            addCriterion("company_telephone not like", value, "companyTelephone");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneIn(List<String> values) {
            addCriterion("company_telephone in", values, "companyTelephone");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneNotIn(List<String> values) {
            addCriterion("company_telephone not in", values, "companyTelephone");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneBetween(String value1, String value2) {
            addCriterion("company_telephone between", value1, value2, "companyTelephone");
            return (Criteria) this;
        }

        public Criteria andCompanyTelephoneNotBetween(String value1, String value2) {
            addCriterion("company_telephone not between", value1, value2, "companyTelephone");
            return (Criteria) this;
        }

        public Criteria andMarkRegistrationNoIsNull() {
            addCriterion("mark_registration_no is null");
            return (Criteria) this;
        }

        public Criteria andMarkRegistrationNoIsNotNull() {
            addCriterion("mark_registration_no is not null");
            return (Criteria) this;
        }

        public Criteria andMarkRegistrationNoEqualTo(Integer value) {
            addCriterion("mark_registration_no =", value, "markRegistrationNo");
            return (Criteria) this;
        }

        public Criteria andMarkRegistrationNoNotEqualTo(Integer value) {
            addCriterion("mark_registration_no <>", value, "markRegistrationNo");
            return (Criteria) this;
        }

        public Criteria andMarkRegistrationNoGreaterThan(Integer value) {
            addCriterion("mark_registration_no >", value, "markRegistrationNo");
            return (Criteria) this;
        }

        public Criteria andMarkRegistrationNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("mark_registration_no >=", value, "markRegistrationNo");
            return (Criteria) this;
        }

        public Criteria andMarkRegistrationNoLessThan(Integer value) {
            addCriterion("mark_registration_no <", value, "markRegistrationNo");
            return (Criteria) this;
        }

        public Criteria andMarkRegistrationNoLessThanOrEqualTo(Integer value) {
            addCriterion("mark_registration_no <=", value, "markRegistrationNo");
            return (Criteria) this;
        }

        public Criteria andMarkRegistrationNoIn(List<Integer> values) {
            addCriterion("mark_registration_no in", values, "markRegistrationNo");
            return (Criteria) this;
        }

        public Criteria andMarkRegistrationNoNotIn(List<Integer> values) {
            addCriterion("mark_registration_no not in", values, "markRegistrationNo");
            return (Criteria) this;
        }

        public Criteria andMarkRegistrationNoBetween(Integer value1, Integer value2) {
            addCriterion("mark_registration_no between", value1, value2, "markRegistrationNo");
            return (Criteria) this;
        }

        public Criteria andMarkRegistrationNoNotBetween(Integer value1, Integer value2) {
            addCriterion("mark_registration_no not between", value1, value2, "markRegistrationNo");
            return (Criteria) this;
        }

        public Criteria andFaxIsNull() {
            addCriterion("fax is null");
            return (Criteria) this;
        }

        public Criteria andFaxIsNotNull() {
            addCriterion("fax is not null");
            return (Criteria) this;
        }

        public Criteria andFaxEqualTo(String value) {
            addCriterion("fax =", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotEqualTo(String value) {
            addCriterion("fax <>", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxGreaterThan(String value) {
            addCriterion("fax >", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxGreaterThanOrEqualTo(String value) {
            addCriterion("fax >=", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLessThan(String value) {
            addCriterion("fax <", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLessThanOrEqualTo(String value) {
            addCriterion("fax <=", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLike(String value) {
            addCriterion("fax like", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotLike(String value) {
            addCriterion("fax not like", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxIn(List<String> values) {
            addCriterion("fax in", values, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotIn(List<String> values) {
            addCriterion("fax not in", values, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxBetween(String value1, String value2) {
            addCriterion("fax between", value1, value2, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotBetween(String value1, String value2) {
            addCriterion("fax not between", value1, value2, "fax");
            return (Criteria) this;
        }

        public Criteria andTaxCodeIsNull() {
            addCriterion("tax_code is null");
            return (Criteria) this;
        }

        public Criteria andTaxCodeIsNotNull() {
            addCriterion("tax_code is not null");
            return (Criteria) this;
        }

        public Criteria andTaxCodeEqualTo(String value) {
            addCriterion("tax_code =", value, "taxCode");
            return (Criteria) this;
        }

        public Criteria andTaxCodeNotEqualTo(String value) {
            addCriterion("tax_code <>", value, "taxCode");
            return (Criteria) this;
        }

        public Criteria andTaxCodeGreaterThan(String value) {
            addCriterion("tax_code >", value, "taxCode");
            return (Criteria) this;
        }

        public Criteria andTaxCodeGreaterThanOrEqualTo(String value) {
            addCriterion("tax_code >=", value, "taxCode");
            return (Criteria) this;
        }

        public Criteria andTaxCodeLessThan(String value) {
            addCriterion("tax_code <", value, "taxCode");
            return (Criteria) this;
        }

        public Criteria andTaxCodeLessThanOrEqualTo(String value) {
            addCriterion("tax_code <=", value, "taxCode");
            return (Criteria) this;
        }

        public Criteria andTaxCodeLike(String value) {
            addCriterion("tax_code like", value, "taxCode");
            return (Criteria) this;
        }

        public Criteria andTaxCodeNotLike(String value) {
            addCriterion("tax_code not like", value, "taxCode");
            return (Criteria) this;
        }

        public Criteria andTaxCodeIn(List<String> values) {
            addCriterion("tax_code in", values, "taxCode");
            return (Criteria) this;
        }

        public Criteria andTaxCodeNotIn(List<String> values) {
            addCriterion("tax_code not in", values, "taxCode");
            return (Criteria) this;
        }

        public Criteria andTaxCodeBetween(String value1, String value2) {
            addCriterion("tax_code between", value1, value2, "taxCode");
            return (Criteria) this;
        }

        public Criteria andTaxCodeNotBetween(String value1, String value2) {
            addCriterion("tax_code not between", value1, value2, "taxCode");
            return (Criteria) this;
        }

        public Criteria andEMailIsNull() {
            addCriterion("e_mail is null");
            return (Criteria) this;
        }

        public Criteria andEMailIsNotNull() {
            addCriterion("e_mail is not null");
            return (Criteria) this;
        }

        public Criteria andEMailEqualTo(String value) {
            addCriterion("e_mail =", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotEqualTo(String value) {
            addCriterion("e_mail <>", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailGreaterThan(String value) {
            addCriterion("e_mail >", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailGreaterThanOrEqualTo(String value) {
            addCriterion("e_mail >=", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLessThan(String value) {
            addCriterion("e_mail <", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLessThanOrEqualTo(String value) {
            addCriterion("e_mail <=", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLike(String value) {
            addCriterion("e_mail like", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotLike(String value) {
            addCriterion("e_mail not like", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailIn(List<String> values) {
            addCriterion("e_mail in", values, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotIn(List<String> values) {
            addCriterion("e_mail not in", values, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailBetween(String value1, String value2) {
            addCriterion("e_mail between", value1, value2, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotBetween(String value1, String value2) {
            addCriterion("e_mail not between", value1, value2, "eMail");
            return (Criteria) this;
        }

        public Criteria andWebsiteIsNull() {
            addCriterion("website is null");
            return (Criteria) this;
        }

        public Criteria andWebsiteIsNotNull() {
            addCriterion("website is not null");
            return (Criteria) this;
        }

        public Criteria andWebsiteEqualTo(String value) {
            addCriterion("website =", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotEqualTo(String value) {
            addCriterion("website <>", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteGreaterThan(String value) {
            addCriterion("website >", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteGreaterThanOrEqualTo(String value) {
            addCriterion("website >=", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteLessThan(String value) {
            addCriterion("website <", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteLessThanOrEqualTo(String value) {
            addCriterion("website <=", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteLike(String value) {
            addCriterion("website like", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotLike(String value) {
            addCriterion("website not like", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteIn(List<String> values) {
            addCriterion("website in", values, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotIn(List<String> values) {
            addCriterion("website not in", values, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteBetween(String value1, String value2) {
            addCriterion("website between", value1, value2, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotBetween(String value1, String value2) {
            addCriterion("website not between", value1, value2, "website");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIsNull() {
            addCriterion("company_type is null");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIsNotNull() {
            addCriterion("company_type is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeEqualTo(String value) {
            addCriterion("company_type =", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotEqualTo(String value) {
            addCriterion("company_type <>", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeGreaterThan(String value) {
            addCriterion("company_type >", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("company_type >=", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLessThan(String value) {
            addCriterion("company_type <", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLessThanOrEqualTo(String value) {
            addCriterion("company_type <=", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLike(String value) {
            addCriterion("company_type like", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotLike(String value) {
            addCriterion("company_type not like", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIn(List<String> values) {
            addCriterion("company_type in", values, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotIn(List<String> values) {
            addCriterion("company_type not in", values, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeBetween(String value1, String value2) {
            addCriterion("company_type between", value1, value2, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotBetween(String value1, String value2) {
            addCriterion("company_type not between", value1, value2, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIsNull() {
            addCriterion("company_address is null");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIsNotNull() {
            addCriterion("company_address is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressEqualTo(String value) {
            addCriterion("company_address =", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotEqualTo(String value) {
            addCriterion("company_address <>", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressGreaterThan(String value) {
            addCriterion("company_address >", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressGreaterThanOrEqualTo(String value) {
            addCriterion("company_address >=", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLessThan(String value) {
            addCriterion("company_address <", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLessThanOrEqualTo(String value) {
            addCriterion("company_address <=", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLike(String value) {
            addCriterion("company_address like", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotLike(String value) {
            addCriterion("company_address not like", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIn(List<String> values) {
            addCriterion("company_address in", values, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotIn(List<String> values) {
            addCriterion("company_address not in", values, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressBetween(String value1, String value2) {
            addCriterion("company_address between", value1, value2, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotBetween(String value1, String value2) {
            addCriterion("company_address not between", value1, value2, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerIsNull() {
            addCriterion("company_power is null");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerIsNotNull() {
            addCriterion("company_power is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerEqualTo(String value) {
            addCriterion("company_power =", value, "companyPower");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerNotEqualTo(String value) {
            addCriterion("company_power <>", value, "companyPower");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerGreaterThan(String value) {
            addCriterion("company_power >", value, "companyPower");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerGreaterThanOrEqualTo(String value) {
            addCriterion("company_power >=", value, "companyPower");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerLessThan(String value) {
            addCriterion("company_power <", value, "companyPower");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerLessThanOrEqualTo(String value) {
            addCriterion("company_power <=", value, "companyPower");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerLike(String value) {
            addCriterion("company_power like", value, "companyPower");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerNotLike(String value) {
            addCriterion("company_power not like", value, "companyPower");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerIn(List<String> values) {
            addCriterion("company_power in", values, "companyPower");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerNotIn(List<String> values) {
            addCriterion("company_power not in", values, "companyPower");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerBetween(String value1, String value2) {
            addCriterion("company_power between", value1, value2, "companyPower");
            return (Criteria) this;
        }

        public Criteria andCompanyPowerNotBetween(String value1, String value2) {
            addCriterion("company_power not between", value1, value2, "companyPower");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationIsNull() {
            addCriterion("company_corporation is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationIsNotNull() {
            addCriterion("company_corporation is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationEqualTo(String value) {
            addCriterion("company_corporation =", value, "companyCorporation");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationNotEqualTo(String value) {
            addCriterion("company_corporation <>", value, "companyCorporation");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationGreaterThan(String value) {
            addCriterion("company_corporation >", value, "companyCorporation");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationGreaterThanOrEqualTo(String value) {
            addCriterion("company_corporation >=", value, "companyCorporation");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationLessThan(String value) {
            addCriterion("company_corporation <", value, "companyCorporation");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationLessThanOrEqualTo(String value) {
            addCriterion("company_corporation <=", value, "companyCorporation");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationLike(String value) {
            addCriterion("company_corporation like", value, "companyCorporation");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationNotLike(String value) {
            addCriterion("company_corporation not like", value, "companyCorporation");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationIn(List<String> values) {
            addCriterion("company_corporation in", values, "companyCorporation");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationNotIn(List<String> values) {
            addCriterion("company_corporation not in", values, "companyCorporation");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationBetween(String value1, String value2) {
            addCriterion("company_corporation between", value1, value2, "companyCorporation");
            return (Criteria) this;
        }

        public Criteria andCompanyCorporationNotBetween(String value1, String value2) {
            addCriterion("company_corporation not between", value1, value2, "companyCorporation");
            return (Criteria) this;
        }

        public Criteria andDutyNoIsNull() {
            addCriterion("duty_no is null");
            return (Criteria) this;
        }

        public Criteria andDutyNoIsNotNull() {
            addCriterion("duty_no is not null");
            return (Criteria) this;
        }

        public Criteria andDutyNoEqualTo(Integer value) {
            addCriterion("duty_no =", value, "dutyNo");
            return (Criteria) this;
        }

        public Criteria andDutyNoNotEqualTo(Integer value) {
            addCriterion("duty_no <>", value, "dutyNo");
            return (Criteria) this;
        }

        public Criteria andDutyNoGreaterThan(Integer value) {
            addCriterion("duty_no >", value, "dutyNo");
            return (Criteria) this;
        }

        public Criteria andDutyNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("duty_no >=", value, "dutyNo");
            return (Criteria) this;
        }

        public Criteria andDutyNoLessThan(Integer value) {
            addCriterion("duty_no <", value, "dutyNo");
            return (Criteria) this;
        }

        public Criteria andDutyNoLessThanOrEqualTo(Integer value) {
            addCriterion("duty_no <=", value, "dutyNo");
            return (Criteria) this;
        }

        public Criteria andDutyNoIn(List<Integer> values) {
            addCriterion("duty_no in", values, "dutyNo");
            return (Criteria) this;
        }

        public Criteria andDutyNoNotIn(List<Integer> values) {
            addCriterion("duty_no not in", values, "dutyNo");
            return (Criteria) this;
        }

        public Criteria andDutyNoBetween(Integer value1, Integer value2) {
            addCriterion("duty_no between", value1, value2, "dutyNo");
            return (Criteria) this;
        }

        public Criteria andDutyNoNotBetween(Integer value1, Integer value2) {
            addCriterion("duty_no not between", value1, value2, "dutyNo");
            return (Criteria) this;
        }

        public Criteria andManagementModelIsNull() {
            addCriterion("management_model is null");
            return (Criteria) this;
        }

        public Criteria andManagementModelIsNotNull() {
            addCriterion("management_model is not null");
            return (Criteria) this;
        }

        public Criteria andManagementModelEqualTo(String value) {
            addCriterion("management_model =", value, "managementModel");
            return (Criteria) this;
        }

        public Criteria andManagementModelNotEqualTo(String value) {
            addCriterion("management_model <>", value, "managementModel");
            return (Criteria) this;
        }

        public Criteria andManagementModelGreaterThan(String value) {
            addCriterion("management_model >", value, "managementModel");
            return (Criteria) this;
        }

        public Criteria andManagementModelGreaterThanOrEqualTo(String value) {
            addCriterion("management_model >=", value, "managementModel");
            return (Criteria) this;
        }

        public Criteria andManagementModelLessThan(String value) {
            addCriterion("management_model <", value, "managementModel");
            return (Criteria) this;
        }

        public Criteria andManagementModelLessThanOrEqualTo(String value) {
            addCriterion("management_model <=", value, "managementModel");
            return (Criteria) this;
        }

        public Criteria andManagementModelLike(String value) {
            addCriterion("management_model like", value, "managementModel");
            return (Criteria) this;
        }

        public Criteria andManagementModelNotLike(String value) {
            addCriterion("management_model not like", value, "managementModel");
            return (Criteria) this;
        }

        public Criteria andManagementModelIn(List<String> values) {
            addCriterion("management_model in", values, "managementModel");
            return (Criteria) this;
        }

        public Criteria andManagementModelNotIn(List<String> values) {
            addCriterion("management_model not in", values, "managementModel");
            return (Criteria) this;
        }

        public Criteria andManagementModelBetween(String value1, String value2) {
            addCriterion("management_model between", value1, value2, "managementModel");
            return (Criteria) this;
        }

        public Criteria andManagementModelNotBetween(String value1, String value2) {
            addCriterion("management_model not between", value1, value2, "managementModel");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveIsNull() {
            addCriterion("annual_turnove is null");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveIsNotNull() {
            addCriterion("annual_turnove is not null");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveEqualTo(String value) {
            addCriterion("annual_turnove =", value, "annualTurnove");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveNotEqualTo(String value) {
            addCriterion("annual_turnove <>", value, "annualTurnove");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveGreaterThan(String value) {
            addCriterion("annual_turnove >", value, "annualTurnove");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveGreaterThanOrEqualTo(String value) {
            addCriterion("annual_turnove >=", value, "annualTurnove");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveLessThan(String value) {
            addCriterion("annual_turnove <", value, "annualTurnove");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveLessThanOrEqualTo(String value) {
            addCriterion("annual_turnove <=", value, "annualTurnove");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveLike(String value) {
            addCriterion("annual_turnove like", value, "annualTurnove");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveNotLike(String value) {
            addCriterion("annual_turnove not like", value, "annualTurnove");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveIn(List<String> values) {
            addCriterion("annual_turnove in", values, "annualTurnove");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveNotIn(List<String> values) {
            addCriterion("annual_turnove not in", values, "annualTurnove");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveBetween(String value1, String value2) {
            addCriterion("annual_turnove between", value1, value2, "annualTurnove");
            return (Criteria) this;
        }

        public Criteria andAnnualTurnoveNotBetween(String value1, String value2) {
            addCriterion("annual_turnove not between", value1, value2, "annualTurnove");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalIsNull() {
            addCriterion("registered_capital is null");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalIsNotNull() {
            addCriterion("registered_capital is not null");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalEqualTo(String value) {
            addCriterion("registered_capital =", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalNotEqualTo(String value) {
            addCriterion("registered_capital <>", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalGreaterThan(String value) {
            addCriterion("registered_capital >", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalGreaterThanOrEqualTo(String value) {
            addCriterion("registered_capital >=", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalLessThan(String value) {
            addCriterion("registered_capital <", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalLessThanOrEqualTo(String value) {
            addCriterion("registered_capital <=", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalLike(String value) {
            addCriterion("registered_capital like", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalNotLike(String value) {
            addCriterion("registered_capital not like", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalIn(List<String> values) {
            addCriterion("registered_capital in", values, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalNotIn(List<String> values) {
            addCriterion("registered_capital not in", values, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalBetween(String value1, String value2) {
            addCriterion("registered_capital between", value1, value2, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalNotBetween(String value1, String value2) {
            addCriterion("registered_capital not between", value1, value2, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(Integer value) {
            addCriterion("tenant_id =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(Integer value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(Integer value) {
            addCriterion("tenant_id >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(Integer value) {
            addCriterion("tenant_id <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(Integer value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<Integer> values) {
            addCriterion("tenant_id in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<Integer> values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(Integer value1, Integer value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("account_id is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("account_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(Integer value) {
            addCriterion("account_id =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(Integer value) {
            addCriterion("account_id <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(Integer value) {
            addCriterion("account_id >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("account_id >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(Integer value) {
            addCriterion("account_id <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(Integer value) {
            addCriterion("account_id <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<Integer> values) {
            addCriterion("account_id in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<Integer> values) {
            addCriterion("account_id not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(Integer value1, Integer value2) {
            addCriterion("account_id between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(Integer value1, Integer value2) {
            addCriterion("account_id not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNull() {
            addCriterion("address_id is null");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNotNull() {
            addCriterion("address_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddressIdEqualTo(Integer value) {
            addCriterion("address_id =", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotEqualTo(Integer value) {
            addCriterion("address_id <>", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThan(Integer value) {
            addCriterion("address_id >", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("address_id >=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThan(Integer value) {
            addCriterion("address_id <", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThanOrEqualTo(Integer value) {
            addCriterion("address_id <=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdIn(List<Integer> values) {
            addCriterion("address_id in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotIn(List<Integer> values) {
            addCriterion("address_id not in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdBetween(Integer value1, Integer value2) {
            addCriterion("address_id between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotBetween(Integer value1, Integer value2) {
            addCriterion("address_id not between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("updater like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("updater not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("update_time like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("update_time not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table erp_company
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table erp_company
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}